name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - back/announcement-service
          - back/auth-service
          - back/blacklist-service
          - back/chat-service
          - back/comment-service
          - back/discovery-service
          - back/favourite-service
          - back/gateway
          - back/notification-service
          - back/recommendation-service
          - back/user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Install core library
        run: |
          cd back/core
          mvn clean install

      - name: Build with Maven
        run: |
          cd ${{ matrix.service }}
          mvn clean package

      - name: Run tests
        run: |
          cd ${{ matrix.service }}
          mvn test

      - name: Lint with Maven
        run: |
          cd ${{ matrix.service }}
          mvn spotless:check

      - name: Build Docker image
        run: |
          cd ${{ matrix.service }}
          docker build -t re-tail/${{ github.event.repository.name }}:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker push re-tail/${{ github.event.repository.name }}:${{ github.sha }}
