name: Backend CI/CD Pipeline

on:
  pull_request:
    paths:
      - 'back/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - announcement-service
          - auth-service
          - discovery-service
          - favourite-service
          - gateway
          - recommendation-service
          - user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Lint with Checkstyle for ${{ matrix.service }}
        run: |
          cd back/${{ matrix.service }}
          mvn checkstyle:check

  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        service:
          - announcement-service
          - auth-service
          - discovery-service
          - favourite-service
          - gateway
          - recommendation-service
          - user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install core library
        run: |
          cd back/core
          mvn clean install

      - name: Build ${{ matrix.service }} with Maven
        run: |
          cd back/${{ matrix.service }}
          mvn clean package -DskipTests

  tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service:
          - announcement-service
          - auth-service
          - discovery-service
          - favourite-service
          - gateway
          - recommendation-service
          - user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install core library
        run: |
          cd back/core
          mvn clean install

      - name: Run tests for ${{ matrix.service }}
        run: |
          cd back/${{ matrix.service }}
          mvn test

  push_to_docker:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: [lint, build, tests]
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker push re-tail/${{ github.event.repository.name }}:${{ github.sha }}
