name: Backend CI/CD Pipeline

on:
  pull_request:
    paths:
      - 'back/chat-service/**'
jobs:
  build:
    name: Build Chat Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install core library
        run: |
          cd back/core
          mvn clean install

      - name: Build Chat Service with Maven
        run: |
          cd back/chat-service
          mvn clean package -DskipTests

      - name: Run tests for Chat Service
        run: |
          cd back/chat-service
          mvn test

      - name: Lint with Maven for Chat Service
        run: |
          cd back/chat-service
          mvn spotless:check

      - name: Build Docker image for Chat Service
        run: |
          back/chat-service
          docker build -t re-tail/${{ github.event.repository.name }}:${{ github.sha }} .

  push_to_docker:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker push re-tail/${{ github.event.repository.name }}:${{ github.sha }}
